name: "🗺️ Epic"
description: A multi-sprint outcome delivered through multiple Features
title: "🗺️ [EPIC] - <outcome>"
labels: ["epic"]

body:
  - type: markdown
    attributes:
      value: |
        **Epics are outcomes** (usually multi-sprint) delivered through multiple **Features**.
        Use this to describe the *why* and *what “done” looks like*, then create Features as **sub-issues** of this
        Epic.
        Avoid using an Epic as a general “bucket” for unrelated work — keep it one coherent outcome.

  - type: textarea
    id: outcome
    attributes:
      label: "Outcome / goal"
      description: "What are we trying to achieve, for whom, and why now?"
      value: |
        Outcome:
        - (What will be possible / improved when this epic is done?)

        Stakeholders / users impacted:
        - (Operator / customer / support / developer / engineer / quality control / etc.)

        Why now:
        - (What’s driving this? deadline, incident trend, customer need, risk reduction)

        How we’ll measure success (optional):
        - (e.g. time saved, fewer incidents, latency, adoption)
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Scope"
      description: "High-level boundaries. Keep it short and explicit."
      value: |
        In scope:
        - …

        Out of scope:
        - …

        Notes (optional):
        - …
    validations:
      required: false

  - type: textarea
    id: exit_criteria
    attributes:
      label: "Exit criteria (definition of done)"
      description: "Clear conditions for closing this Epic."
      placeholder: |
        - User-facing acceptance criteria met for each Feature
        - Operational readiness complete (docs/runbooks/alerts updated if needed)
        - Any success metric targets met (if defined)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Epic Priority"
      options:
        - "Urgent"
        - "High"
        - "Normal"
        - "Low"
      default: 2
    validations:
      required: true

  - type: input
    id: target_window
    attributes:
      label: "Target window"
      description: "Optional. Prefer a range (e.g. Sprint 14–16, Q1) over a single date."
      placeholder: "e.g. Sprint 14–16"
    validations:
      required: false

  - type: textarea
    id: dependencies_risks
    attributes:
      label: "Dependencies / risks"
      value: |
        Dependencies:
        - (Other teams, vendors, hardware availability, API contracts, etc.)

        Risks:
        - (Unknowns, integration risk, time constraints, safety/ops risk)

        Mitigations (optional):
        - …
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ✅ **After creating this issue:** please add it to the appropriate **Project** using the right-hand sidebar → **Projects**.
        If you’re not sure which Project to use, ask by emailing engineering@assetcool.com.
