name: "💡 Feature"
description: A user-visible slice of value (often 1 sprint)
title: "💡 [FEATURE] - <title>"
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: |
        **Features carry the user story + user-facing acceptance criteria.**
        Break the Feature into Tasks (as sub-issues).

  - type: textarea
    id: user_story
    attributes:
      label: "User story"
      description: "Try to write roughly in the form: As a &lt;user&gt;, I want &lt;capability&gt;, so that &lt;benefit&gt;."
      value: "As a &lt;user&gt;, I want &lt;capability&gt;, so that &lt;benefit&gt;."
    validations:
      required: true

  - type: input
    id: epic_link
    attributes:
      label: "Parent Epic"
      description: "Optional but recommended. Paste issue number (e.g. #123) or full URL to epic."
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance criteria"
      description: "User-facing, testable conditions."
      placeholder: |
        - AC1:
        - AC2:
        - AC3:
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Notes / design / links"
      value: |
        **Story points are relative (not hours). Use them to express overall effort/complexity/uncertainty.**

        **Please use the following as a guide for populating the _Estimate_ field during Sprint Planning:**

        **Quick guide**
        - ?: not enough info to estimate (needs clarification/spike)
        - ½–1: tiny, well understood, low risk
        - 2–3: small, straightforward, some unknowns
        - 5: medium, multiple steps, needs testing
        - 8: large, design decisions / more moving parts
        - 13: very large, high uncertainty — consider splitting
        - 20/40/100: too big/uncertain — break down before committing
        - ∞: unbounded/unestimable as written (re-scope)

        Further explanation: [Why the Fibonacci sequence works well for estimating](https://www.mountaingoatsoftware.com/blog/why-the-fibonacci-sequence-works-well-for-estimating)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ✅ **After creating this issue:** please add it to the appropriate _Project_ using the right-hand sidebar → _Projects_.
        N.B. If you have linked the Feature to an Epic that is already part of this project, the Feature should inherit this.

        At Sprint Planning, once the issue is moved to **Ready** Status, please ensure that a _Priority_ is assigned and an _Estimate_ is given using the guide above.
        If you’re not sure which Project to use, ask by emailing engineering@assetcool.com.
