name: "🧩 Task"
description: A concrete unit of implementation work (sub-issue of a Feature)
title: "🧩 [TASK] - <short title>"
labels: ["task"]

body:
  - type: markdown
    attributes:
      value: |
        **Tasks are engineering deliverables** (implementation work that supports a Feature).
        Best practice: create this Task *from the Feature* using **Create sub-issue** so the hierarchy is correct.
        (Once a feature is created, a `Create sub-issue` button is added above the `comments` section)

  - type: input
    id: feature_link
    attributes:
      label: "Linked Feature"
      description: "Required for traceability. Paste #123 or full URL."
      placeholder: "#123"
    validations:
      required: true

  - type: textarea
    id: task_goal
    attributes:
      label: "Task goal"
      description: "One or two sentences describing what will be delivered."
      placeholder: |
        Implement/Update/Refactor <thing> to <outcome>.
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: "Verification / how to test (optional)"
      description: "How should someone verify this task is done?"
      placeholder: |
        - Steps to verify:
        - Tests to run:
        - Expected result:
    validations:
      required: false

  - type: textarea
    id: implementation_notes
    attributes:
      label: "Implementation notes / links (optional)"
      placeholder: |
        - Approach:
        - Dependencies and Pre-requisites:
        - Related PRs/issues:
        - Edge cases to consider:
    validations:
      required: false

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: "Definition of done"
      options:
        - label: "Work merged/commits made if part of a larger PR"
        - label: "Tests added/updated (if applicable)"
        - label: "Docs updated (if applicable)"
        - label: "The ticket has a readable title and description matches what was done"
