name: "🐛 Bug Report"
description: Create a new issue for a bug.
title: "🐛 [BUG] - <title>"
labels: ["bug"]

body:
  - type: input
    id: related_feature
    attributes:
      label: "Related Feature (optional)"
      description: "If this bug belongs to a known Feature, paste #123 or a full issue URL."
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What’s broken?"
      placeholder: "Short, explicit description of the problem..."
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: "Expected vs actual behaviour"
      placeholder: |
        Expected behaviour:
        Actual behaviour:
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: "Environment / version"
      description: "OS/device, service version, commit SHA, build number, etc."
      placeholder: "e.g. Jetson Orin / Ubuntu 22.04 / bot_system v1.2.3 / commit abc123"
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots."
      placeholder: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Paste relevant logs."
      render: bash
    validations:
      required: false

  - type: textarea
    id: fix_criteria
    attributes:
      label: "Fix criteria (acceptance criteria)"
      description: "How do we know this bug is fixed?"
      placeholder: |
        - No longer reproduces using steps above
        - Added regression test (if applicable)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ✅ **After creating this issue:** please add it to the appropriate _Project_ using the right-hand sidebar → _Projects_.
        N.B. If you have linked the Feature to an Epic that is already part of this project, the Bug should inherit this.

        At Sprint Planning, once the issue is moved to **Ready** Status, please ensure that a _Priority_ is assigned and an _Estimate_ is given.
        If you’re not sure which Project to use, ask by emailing engineering@assetcool.com.
