name: "🧩 Task"
description: A concrete unit of implementation work (sub-issue of a Feature)
title: "🧩 [TASK] - <short title>"
labels: ["task"]

body:
  - type: markdown
    attributes:
      value: |
        **Tasks are engineering deliverables.**
        Best practice: create this Task *from the Feature* using **Create sub-issue** so the hierarchy is correct. :contentReference[oaicite:1]{index=1}

  - type: input
    id: feature_link
    attributes:
      label: "Linked Feature"
      description: "Required for traceability. Paste #123 or full URL."
      placeholder: "#123"
    validations:
      required: true

  - type: textarea
    id: task_goal
    attributes:
      label: "Task goal"
      description: One or two sentences describing what will be delivered.
      placeholder: |
        Implement/Update/Refactor ...
        Notes on expected behaviour:
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance criteria"
      description: "Engineering/testable conditions (can be different from Feature AC)."
      placeholder: |
        - AC1:
        - AC2:
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "P0 - Critical (blocker)"
        - "P1 - High"
        - "P2 - Medium"
        - "P3 - Low"
    validations:
      required: true

  - type: textarea
    id: implementation_notes
    attributes:
      label: "Implementation notes / links"
      placeholder: |
        - Approach:
        - Dependencies:
        - Related PRs/issues:
    validations:
      required: false

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: "Definition of done"
      options:
        - label: "PR linked and merged"
        - label: "Tests added/updated (if applicable)"
        - label: "Docs updated (if applicable)"
